### ISSUE TITLE
How do I install this

### ISSUE THREAD

**Issue by ghost** [OtakuMegane/FarLandsAgain#1]

**Comment by OtakuMegane** [comment]
The compiled plugin is available here as well as installation instructions: https://www.spigotmc.org/resources/farlandsagain.8228/

**Comment by ghost** [comment]
I put the plugin in my plugins folder
and I turned on the server I went to the coordinates of where the far lands should be and it was just normal world that generated

**Comment by OtakuMegane** [comment]
Make sure you edited the config.yml correctly to enable it on the world(s) you want. It doesn't act on any worlds by default, they have to be specified. Then check the console for plugin messages. It should say '[FarLandsAgain Success] The world (world name) will have Far Lands!' upon loading each world you have enabled. If you see any errors related to the plugin, post them here and we can figure out what's wrong.

**Comment by ghost** [comment]
I am trying to get it enabled
but its not showing this message
'[FarLandsAgain Success]'

**Comment by ghost** [comment]
ok I got the message

**Comment by ghost** [comment]
but I don't see far lands when I tp to the coords where the far lands should generate
All I am seeing is normal world generation

**Comment by OtakuMegane** [comment]
Making progress then. :) If you didn't reset the world, the terrain from the first attempts would still be there. Try a couple random coordinates in the Far Lands (as long as one or both coordinates are 12550824 or higher, you'll be in the area). If you still don't see anything, check the console for any kind of errors.

**Comment by ghost** [comment]
The server generated a ocean instead of far lands this is an ocean that was never generated before

**Comment by OtakuMegane** [comment]
Alright let's verify some things and maybe I can reproduce what's happening:
 - Are there any other plugins that would modify terrain or biome generation?
 - Did you make the world with any of the custom settings Mojang added in 1.16?
 - What Minecraft version are you on and is it Spigot or Paper?
 - What is the seed of the world? (type /seed while in-game or in the console)
 - Is it a flat world type?

**Comment by ghost** [comment]
Seed - 6751159050101105924
Minecraft Version is 1.16.5 Yatopia which is fork of Paper
World is default world type
Only other plugin that would affect biome or terain generation is world edit

**Comment by OtakuMegane** [comment]
Regular Spigot and Paper both work fine but sure enough it doesn't work on Yatopia. I'll have to try all the branches it pulls from and see if changes from one of those is interfering. Unfortunately whatever is going on it's apparently happening silently after the generator has been set, which makes things tricky.

**Comment by OtakuMegane** [comment]
After poking around and testing, it appears the problem is a patch to the noise generator made by the Lithium fork and imported by Yatopia. The vanilla logic is replaced for optimizations and the new logic is fixing the overflow that creates the Far Lands. The plugin is functioning and does the modifications as expected but the noise generator cancels it out before returning the final values.
Finding a workaround would likely eat a good amount of time and make initializing the Far Lands generator more complex. If the patch becomes widespread or is pulled into base Paper, this can be revisited. For now it's a no fix.
